# Generated by Django 3.2.1 on 2021-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_milestoneimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
